<?php
declare(strict_types=1);


namespace App\Tests\Model\Cart;

use App\Repository\ProductRepository;
use PHPUnit\Framework\TestCase;

class CartManagerTest extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
    public function testAddProduct(): void
    {
        $str = 'test string';
        $this->assertIsString($str);
        $this->assertNotNull('11');
    }


}
